### ISSUE TITLE
FirebaseMessagingService didn't start after adding dependency 4.6

### ISSUE THREAD

**Issue by andriizhumela** [hypertrack/quickstart-android#23]
FirebaseMessagingService didn't start after adding dependency 4.6

We have a part of logic inside FirebaseMessagingService (creating custom notification channels etc.).
After adding dependency `implementation 'com.hypertrack:hypertrack:4.6.0'` this service don't start at all.

**Comment by andriizhumela** [comment]
@deniszpua 
UPD: Previously we use 3.3.1 and all was work fine, but after update to 4.6 this service wont start. 

More than, we commented all places where call HyperTrack methods (we left only dependency in gradle).
FirebaseService start only after remove all from gradle.

**Comment by deniszpua** [comment]
@andriizhumela we use firebase messaging as a transport for server to device communication, so the service is added to your app automatically, once you've added dependency to gradle. Since it runs with somewhat higher priority then `FirebaseMessagingService` it handles all the push notifications, so I'ld recommend you to extend it instead of Firebase.
You can use our [logistic app as a sample](https://github.com/hypertrack/logistics-android/blob/v0.2.5/app/src/main/java/com/hypertrack/android/messaging/VisitsMessagingService.kt).
HTH
